export const CredentialProvider = {
  META_ADS: "META_ADS",
  GOOGLE_ADS: "GOOGLE_ADS",
  PAYPAL: "PAYPAL",
  STRIPE: "STRIPE",
  SHOPIFY_PAYMENTS: "SHOPIFY_PAYMENTS",
  BING_ADS: "BING_ADS",
  TIKTOK_ADS: "TIKTOK_ADS",
  KLARNA: "KLARNA",
  AMAZON_ADS: "AMAZON_ADS",
  SNAPCHAT_ADS: "SNAPCHAT_ADS",
  EASYPOST_LOGISTICS: "EASYPOST_LOGISTICS",
  SHIPSTATION_LOGISTICS: "SHIPSTATION_LOGISTICS",
};

export const AttributionRuleType = {
  LAST_TOUCH: "LAST_TOUCH",
  FIRST_TOUCH: "FIRST_TOUCH",
};

export const GdprRequestType = {
  EXPORT: "EXPORT",
  DELETE: "DELETE",
};

export const GdprRequestStatus = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};
